---
# The default profile (Available in application.properties) is used when running a single instance completely standalone:
# primary, secondary, and tertiary are running 3 intercommunicating instances.  
# Run by opening 3 separate command prompts:
# java -jar -Dspring.profiles.active=DEV-PRIMARY eureka-server-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=DEV-SECONDARY eureka-server-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=DEV-TERTIARY eureka-server-0.0.1-SNAPSHOT.jar

spring:   
#  profiles: DEV-PRIMARY
  config: 
    activate.on-profile: STANDALONE 
  application:
    name: eureka-server-standalone 
server:
  port: 8761  
eureka: 
  instance:
    ipAddress: 127.0.0.1
    hostname: ${eureka.instance.ip-address}
