--- 
## DEV Profile

spring:
  config: 
    activate.on-profile: SBA,ADEV-PRIMARY,DEV-PRIMARY,DEV-SECONDARY,DEV-TERTIARY 
  zipkin:
     base-url: http://localhost:9411 
  boot:
    admin:
      client:
        instance:
          service-base-url: http://localhost:7126
        
--- 
## UDEV Profile

spring:
  config: 
    activate.on-profile: SBA,UDEV-PRIMARY,UDEV-SECONDARY,UDEV-TERTIARY 
  zipkin:
     base-url: http://localhost:9411 
  boot:
    admin:
      client:
        instance:
          service-base-url: http://localhost:7126
          
---

## PRO Profile

spring: 
  config: 
    activate.on-profile: SBA,PRO-PRIMARY,PRO-SECONDARY,PRO-TERTIARY 
  zipkin:
     base-url: http://172.19.250.8:9411 
  boot:
    admin:
      client:
        instance:
          service-base-url: http://172.19.250.8:7126