---
# The default profile (Available in application.properties) is used when running a single instance completely standalone:
# primary, secondary, and tertiary are running 3 intercommunicating instances.  
# Run by opening 3 separate command prompts:
# java -jar -Dspring.profiles.active=primary lab-4-eureka-server-solution-1.jar
# java -jar -Dspring.profiles.active=secondary lab-4-eureka-server-solution-1.jar
# java -jar -Dspring.profiles.active=tertiary lab-4-eureka-server-solution-1.jar
spring: 
   boot:
      admin:
         client:
            instance:
              service-base-url: http://localhost:7126
            url: ${spring.boot.admin.client.service-base-url}
   zipkin:
      base-url: http://localhost:9411
      
   profiles: primary
   application:
    name: eureka-server-clustered   
server:
  port: 8762  
eureka:
  instance:
    hostname: eureka-primary
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2       
  client:
    registerWithEureka: true
    fetchRegistry: true        
    serviceUrl:
      defaultZone: http://thirumal:thirumal@localhost:8763/eureka/,http://thirumal:thirumal@localhost:8764/eureka/, http://thirumal:thirumal@localhost:8761/eureka/

---
spring:
  profiles: secondary
  application:
    name: eureka-server-clustered      
server:
  port: 8763
eureka:
  instance:
    hostname: eureka-secondary       
  client:
    registerWithEureka: true
    fetchRegistry: true        
    serviceUrl:
      defaultZone: http://thirumal:thirumal@localhost:8764/eureka/,http://thirumal:thirumal@localhost:8762/eureka/

---
spring:
  profiles: tertiary
  application:
    name: eureka-server-clustered      
server:
  port: 8764
eureka:
  instance:
    hostname: eureka-tertiary       
  client:
    registerWithEureka: true
    fetchRegistry: true    
    serviceUrl:
      defaultZone: http://thirumal:thirumal@localhost:8762/eureka/,http://thirumal:thirumal@localhost:8763/eureka/      
