---
# The default profile (Available in application.properties) is used when running a single instance completely standalone:
# primary, secondary, and tertiary are running 3 intercommunicating instances.  
# Run by opening 3 separate command prompts:
# java -jar -Dspring.profiles.active=DEV-PRIMARY eureka-server-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=DEV-SECONDARY eureka-server-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=DEV-TERTIARY eureka-server-0.0.1-SNAPSHOT.jar

spring:   
#  profiles: DEV-PRIMARY
  config: 
    activate.on-profile: PRO-PRIMARY
  application:
    name: eureka-server-clustered-1 
server:
  port: 8761  
eureka: 
  instance:
    hostname: 172.19.250.7
    ipAddress: ${eureka.instance.hostname}   
  client:        
    serviceUrl:
      defaultZone: http://thirumal:thirumal@172.19.250.8:8762/eureka/,http://thirumal:thirumal@172.19.250.9:8763/eureka/
      
      
---

spring: 
#  profiles: DEV-SECONDARY
  config: 
    activate.on-profile: PRO-SECONDARY
  application:
    name: eureka-server-clustered-2  
server:
  port: 8762
eureka:
  instance:
    hostname: 172.19.250.8
    ipAddress: 172.19.250.8     
  client:
    serviceUrl:
      defaultZone: http://thirumal:thirumal@172.19.250.7:8761/eureka/,http://thirumal:thirumal@172.19.250.9:8763/eureka/

---

spring: 
#  profiles: DEV-TERTIARY
  config: 
    activate.on-profile: PRO-TERTIARY
  application:
    name: eureka-server-clustered-3    
server:
  port: 8763
eureka:
  instance:
    hostname: 172.19.250.9
    ipAddress: ${eureka.instance.hostname} 
  client:
    serviceUrl:
      defaultZone: http://thirumal:thirumal@172.19.250.7:8761/eureka/,http://thirumal:thirumal@172.19.250.8:8762/eureka/      

