---
# The default profile (Available in application.properties) is used when running a single instance completely standalone:
# primary, secondary, and tertiary are running 3 intercommunicating instances.  
# Run by opening 3 separate command prompts:
# java -jar -Dspring.profiles.active=DEV-PRIMARY eureka-server-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=DEV-SECONDARY eureka-server-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=DEV-TERTIARY eureka-server-0.0.1-SNAPSHOT.jar

spring:   
#  profiles: DEV-PRIMARY
  config: 
    activate.on-profile: UDEV-PRIMARY 
  application:
    name: eureka-server-clustered-1 
server:
  port: 8761  
eureka: 
  instance:
    ipAddress: 192.168.0.17
    hostname: eureka-primary
  client:       
    serviceUrl:
      defaultZone: http://thirumal:thirumal@192.168.0.27:8763/eureka/
      
      
---

spring: 
#  profiles: DEV-SECONDARY
  config: 
    activate.on-profile: UDEV-SECONDARY 
  application:
    name: eureka-server-clustered-2  
server:
  port: 8762
eureka:
  instance:
    ipAddress: 192.168.0.17
    hostname: eureka-secondary      
  client:       
    serviceUrl:
     defaultZone: http://thirumal:thirumal@192.168.0.17:8761/eureka/,http://thirumal:thirumal@192.168.0.27:8763/eureka/

---

spring: 
#  profiles: DEV-TERTIARY
  config: 
    activate.on-profile: UDEV-TERTIARY 
  application:
    name: eureka-server-clustered-3    
server:
  port: 8763
eureka:
  instance:
    ipAddress: 192.168.0.27
    hostname: eureka-tertiary      
  client:    
    serviceUrl:
      defaultZone: http://thirumal:thirumal@192.168.0.17:8761/eureka/      

